use ESCUELA
/*tiene que ser index alv*/
Create view Edad_alumno AS(
	SELECT *
	FROM ALLUMNO
	ORDER BY EDAD DESC
);




CREATE VIEW PROFESORES AS(
SELECT SALON, NOM_PROF, NOM_ALUM
FROM ALUMNO_GRUPO AG
INNERJOIN ALUMNO A
ON AG.BOLETA=A.BOLETA
INNERJOIN GRUPO G
AG.GRUPO=G.GRUPO
INNERJOIN PROFESORES
ON RFC=CVE_PROFESOR;

CREATE VIEW TODAS:CARRERAS AS(
SELECT C.DESCRIPCION, M.DESCRIPCION
FROM CARRERA, MATTERIA);

CREATE VIEX PROFESOR_BASE AS(
SELECT *
FROM PROFESOR_BASE
UNION
SELECT *
FROM PROFESOR_INTERINO);

CREATE VIEW PROFESOR AS(
SELECT * PROFESOR_INTERINO
EXCEOT
SELECT *PROFESOR_BASE

CREATE VIEW PROFESORES AS(
SELECT *FROM PROFESOR_BASE
INTERSECT
SELECT *FROM PROFESOR_EXTERIORES

CREATE VIEW MATERIA AS(º
SELECT M.DESCRIPCION,G.SECUENCIA
FORM MATERIA M
INNERJOIN GRUPO G ON M CLAVE MATERIA=G CLAVE_MATERIA
WHERE M,CREDITOS <9;



/*
=================================================================
			LOS CHIDOS
				DEFINICION
=================================================================
*/


/*
	b
*/
CREATE PROCEDURE ID_GRUPO_ACTUALIZA    
    @OLD_GRUPO INT,
    @NEW_GRUPO INT
AS   
	UPDATE ALUMNO_GRUPO
	SET GRUPO = @NEW_GRUPO
	WHERE GRUPO = @OLD_GRUPO;

	SELECT * FROM ALUMNO_GRUPO;
GO
/*
	c
*/
CREATE PROCEDURE PA_INSERTAR_ALUMNO
	@BOLETA 		INT,
	@NOM_ALUMNO 	VARCHAR (50),
	@EDAD 			INT
AS
	INSERT INTO ALUMNO (BOLETA, NOM_ALUMNO, EDAD)
	VALUES (@BOLETA, @NOM_ALUMNO, @EDAD);
	select * from ALUMNO;
GO
/*
	d
*/
CREATE PROCEDURE GRUPO_ACTUALIZAR
	@ID_GRUPO INT,
	@SALON VARCHAR (10)
AS
	SELECT * FROM GRUPO WHERE ID_GRUPO = @ID_GRUPO;

	UPDATE GRUPO
	SET SALON= @SALON
	WHERE ID_GRUPO=@ID_GRUPO;

	SELECT * FROM GRUPO WHERE ID_GRUPO = @ID_GRUPO;
GO
/*
	e
*/
CREATE PROCEDURE PA_ELIMINAR_PROFESOR
	@RFC VARCHAR (30)
AS
	DELETE PROFESOR_BASE
	WHERE RFC=@RFC
	select * from PROFESOR_BASE;
go
/*
=================================================================
			LOS CHIDOS
				CALLS
=================================================================
*/
/*
	b
*/
EXEC ID_GRUPO_ACTUALIZA N'3', N'34'
/*
	c
*/
EXEC PA_INSERTAR_ALUMNO 200998, 'ALMA MARTINEZ', 17;
/*
	d
*/
EXEC GRUPO_ACTUALIZAR 2, 'LIGEROS 1';
/*
	e
*/
EXEC PA_ELIMINAR_PROFESOR 'DUAX580816';
